trigger:
  branches:
    include:
      - main
      - develop

pr:
  branches:
    include:
      - main
      - develop

parameters:
  - name: nodeVersion
    type: string
    default: '24.x'
  - name: pnpmVersion
    type: string
    default: '10.6.0'
  - name: buildConfiguration
    type: string
    default: 'production'

resources:
  repositories:
    - repository: cicd-pipelines
      type: git
      name: DevOps/cicd-pipelines
      ref: refs/heads/feature/ui-cicd-vue

stages:
  - template: ci/ui-build-vue.yml@cicd-pipelines
    parameters:
      nodeVersion: ${{ parameters.nodeVersion }}
      pnpmVersion: ${{ parameters.pnpmVersion }}
      repoName: 'reference-app-laravel-vue'
      appName: 'ui-kit'
      packageFilter: 'ui-kit'
      packagePath: 'libs/ui-kit'
      buildConfiguration: ${{ parameters.buildConfiguration }}
      stageName: 'BuildUIKit'
